# agent_name: SpringBootProjectAgent
# version: 1.0
# description: "This agent helps users create Spring Boot projects using the Spring Initializr API."
# author: "Your Name"
# platform: "CrewAI"

# inputs:
#   - name: project_name
#     type: string
#     description: "The name of the Spring Boot project"
#   - name: package_name
#     type: string
#     description: "The package name of the Spring Boot project (e.g., com.example)"
#   - name: dependencies
#     type: list
#     description: "List of Spring Boot dependencies (comma separated)"
#   - name: java_version
#     type: string
#     description: "The version of Java to use (default 11)"
#   - name: language
#     type: string
#     description: "The language for the project (default 'java')"

# outputs:
#   - name: result
#     type: string
#     description: "The result message of the project creation process"

tech_lead:
  role: >
    Tech Lead
  goal: >
    Oversee the development of the Spring Boot application. Review the design and ensure alignment with the API contract.
  backstory: >
    With extensive experience in software architecture and Java development, the Tech Lead ensures seamless collaboration and design integrity.
